services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.ssh:/root/.ssh:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["sh", "-c", "npm install && npm start"]
